version: '3'
services:
  typescript-express:
    build:
      context: . 
      # args:
      #   - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
    - NODE_ENV=development
    - CLIENT=http://localhost:3001
    command: npm run dev