name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '44 10 * * 6'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    timeout-minutes: ${{ matrix.language == 'swift' && 120 || 360 }}

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"

  eslint:
      name: Run eslint scanning
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3  
        - name: Install ESLint
          run: |
                  npm install eslint@8.10.0
                  npm install @microsoft/eslint-formatter-sarif@2.1.7
        - name: Run ESLint
          run: npx eslint .
                  --config .eslintrc.js
                  --ext .js,.jsx,.ts,.tsx
                  --format @microsoft/eslint-formatter-sarif
                  --output-file eslint-results.sarif
          continue-on-error: true
        
        - name: Upload analysis results to GitHub
          uses: github/codeql-action/upload-sarif@v2
          with:
                  sarif_file: eslint-results.sarif
                  wait-for-processing: true 